[project]
name = "python"
version = "1.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["requests~=2.32.0", "pandas~=2.2.3", "python-dateutil~=2.9.0", "pip-system-certs~=5.2"]
